CREATE DATABASE QLTIENNET

USE  QLTIENNET

CREATE TABLE KHACHHANG(
	MAKH INT CONSTRAINT PK_KH PRIMARY KEY,
	HOTEN VARCHAR(50),
	NGAYSINH SMALLDATETIME,
	SDT VARCHAR(11),
	GIOITINH VARCHAR(3),
)

CREATE TABLE DICHVU(
	MADV VARCHAR(5) CONSTRAINT PK_DV PRIMARY KEY,
	TENDV VARCHAR(50),
	LOAIDV VARCHAR(20),
	PHI MONEY,
	MOTA VARCHAR(255),
)

CREATE TABLE HOPDONG(
	MAHD VARCHAR(10) CONSTRAINT PK_HD PRIMARY KEY,
	MAKH INT,
	NGAYKY SMALLDATETIME,
)

CREATE TABLE CTHD(
	MAHD VARCHAR(10),
	MADV VARCHAR(5),
	TRANGTHAI VARCHAR(5),
	CONSTRAINT PK_CTHD PRIMARY KEY(MAHD,MADV)
)

ALTER TABLE HOPDONG
ADD CONSTRAINT FK_HD_KH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE	CTHD
ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY(MAHD) REFERENCES HOPDONG(MAHD)

ALTER TABLE	CTHD
ADD CONSTRAINT FK_CTHD_DV FOREIGN KEY(MADV) REFERENCES DICHVU(MADV)

SET DATEFORMAT DMY

INSERT INTO KHACHHANG VALUES(1,'LE HOANG NGUYEN','25/03/2001','0773577204','NAM')
INSERT INTO KHACHHANG VALUES(2,'PHAN ANH NHAT','26/03/2001','0352977905','NAM')
INSERT INTO KHACHHANG VALUES(3,'TRAN NGOC GIAO','25/02/2001',NULL,'NU')

INSERT INTO DICHVU VALUES('DV01','INTERNET TOC DO CAO','INTERNET',220000,'TOC DO UPLOAD: 5MB/S, DOWNLOAD: 10MB/S')
INSERT INTO DICHVU VALUES('DV02','INTERNET TOC DO THUONG','INTERNET',165000,'TOC DO UPLOAD: 1MB/S, DOWNLOAD: 5MB/S')
INSERT INTO DICHVU VALUES('DV03','MYTV++','TRUYEN HINH CAP',200000,'XEM DUOC 200 KENH HD')

INSERT INTO HOPDONG VALUES(1,1,'26/4/2020')
INSERT INTO HOPDONG VALUES(2,2,'26/5/2020')
INSERT INTO HOPDONG VALUES(3,2,'29/5/2020')
INSERT INTO HOPDONG VALUES(4,1,'15/5/2020')
INSERT INTO HOPDONG VALUES(5,1,'16/5/2020')

SELECT *FROM KHACHHANG
SELECT *FROM DICHVU
SELECT *FROM HOPDONG
SELECT *FROM CTHD 

DROP TRIGGER UPDATE_KH

CREATE TRIGGER INSERT_UPDATE_HD ON HOPDONG
FOR INSERT, UPDATE
AS 
BEGIN
	DECLARE @NGAYKY SMALLDATETIME, @NGAYSINH SMALLDATETIME, @MAKH INT
	
	SELECT @MAKH=MAKH, @NGAYKY=NGAYKY
	FROM INSERTED

	SELECT @NGAYSINH=NGAYSINH
	FROM KHACHHANG
	WHERE @MAKH=MAKH
	
	IF(@NGAYSINH>=@NGAYKY)
		BEGIN
			PRINT 'ERROR: LOI DANG KI'
			ROLLBACK TRANSACTION
		END
	ELSE
		BEGIN
			PRINT 'THEM THANH CONG'
		END
END

UPDATE KHACHHANG
SET NGAYSINH='26/03/2001'
WHERE MAKH=1

INSERT INTO HOPDONG VALUES(6,1,'26/3/2001')


CREATE TRIGGER UPDATE_KH ON KHACHHANG
FOR UPDATE
AS
BEGIN
	DECLARE @NGAYKY SMALLDATETIME, @NGAYSINH SMALLDATETIME, @MAKH INT, @MAHD VARCHAR(10)
	
	SELECT @MAKH=MAKH, @NGAYSINH=NGAYSINH
	FROM INSERTED

	DECLARE CURSOR_HD_DK CURSOR FOR
		SELECT MAHD 
		FROM HOPDONG
		WHERE MAKH=@MAKH
	OPEN CURSOR_HD_DK
		FETCH NEXT FROM CURSOR_HD_DK INTO @MAHD
		WHILE @@FETCH_STATUS=0
		BEGIN
			SELECT @NGAYKY=NGAYKY
			FROM HOPDONG
			WHERE MAHD=@MAHD

			IF(@NGAYKY<@NGAYSINH)
				BEGIN
					PRINT 'ERROR: LOI NGAY DANG KY'
					ROLLBACK TRANSACTION
				END
			ELSE
				BEGIN
					FETCH NEXT FROM CURSOR_HD_DK
					INTO @MAHD
				END
		END
	CLOSE CURSOR_HD_DK
	PRINT 'THANH CONG'
	DEALLOCATE CURSOR_HD_DK
END
