DROP DATABASE QLNHATRO
CREATE DATABASE QLNHATRO

USE QLNHATRO

CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(5) CONSTRAINT PK_KH PRIMARY KEY,
	TENKH VARCHAR(50) NOT NULL,
	DIACHI VARCHAR(50),
	CMND VARCHAR(50),
	MAPT VARCHAR(5)
)

CREATE TABLE CHUNHA
(
	MACN VARCHAR (5) CONSTRAINT PK_CN PRIMARY KEY,
	TENCN VARCHAR(50) NOT NULL,
	DIACHI VARCHAR(50),
	CMND VARCHAR(50)
)

CREATE TABLE PHONGTRO
(
	MAPT VARCHAR (5) CONSTRAINT PK_PT PRIMARY KEY,
	MACN VARCHAR(5),
	GIATHUE MONEY DEFAULT 500000,
	MAKH VARCHAR(5) 
)

CREATE TABLE THANHTOAN
(
	SOHD VARCHAR(5) CONSTRAINT PK_TT PRIMARY KEY,
	MAKH VARCHAR(5),
	MAPT VARCHAR(5),
	NGAYNOP SMALLDATETIME,
	SOTIEN MONEY
)

ALTER TABLE KHACHHANG
ADD CONSTRAINT Fk_KH_PT FOREIGN KEY (MAPT) REFERENCES PHONGTRO(MAPT)

ALTER TABLE PHONGTRO
ADD CONSTRAINT Fk_PT_CN FOREIGN KEY (MACN) REFERENCES CHUNHA(MACN)

ALTER TABLE PHONGTRO
ADD CONSTRAINT Fk_PT_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE THANHTOAN 
ADD CONSTRAINT Fk_TT_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE THANHTOAN
ADD CONSTRAINT Fk_TT_PT FOREIGN KEY (MAPT) REFERENCES PHONGTRO(MAPT)

SET DATEFORMAT DMY

INSERT INTO KHACHHANG VALUES ('KH01', 'Nguyen Van A', 'TP HCM', '001122334', 'PT001')
INSERT INTO KHACHHANG VALUES ('KH02', 'Tran Van B', 'Da Nang', '002211334', 'PT002')
INSERT INTO KHACHHANG VALUES ('KH03', 'Huynh Thi C', 'Nha Trang', '331122004', 'PT003')

INSERT INTO CHUNHA VALUES ('CN01', 'Le Cong D', 'Quan 9', '001234567')
INSERT INTO CHUNHA VALUES ('CN02', 'Ngo Thanh E', 'Di An'	, '007654321')
INSERT INTO CHUNHA VALUES ('CN03', 'Cong Tang F', 'Thu Duc', '123456700')

INSERT INTO PHONGTRO VALUES ('PT001', 'CN01', '800000', 'KH01')
INSERT INTO PHONGTRO VALUES ('PT002', 'CN02', '700000',	'KH02')
INSERT INTO PHONGTRO VALUES ('PT003', 'CN03', '900000',	'KH03')

INSERT INTO THANHTOAN VALUES ('00001', 'KH01', 'PT001', '1/2/2019', '800000')
INSERT INTO THANHTOAN VALUES ('00002', 'KH02', 'PT002', '5/2/2019', '700000')
INSERT INTO THANHTOAN VALUES ('00003', 'KH03', 'PT003', '3/2/2019', '900000')

INSERT INTO THANHTOAN VALUES ('00004', 'KH01', 'PT002', '5/2/2019', '700000')
INSERT INTO THANHTOAN VALUES ('00005', 'KH01', 'PT003', '3/2/2019', '900000')

--3.Hiện thực ràng buộc toàn vẹn sau: khách hàng đại diện cho phòng (nếu có) phải ở trọ trong phòng đó (2đ).
DROP TRIGGER TRIGGER_UPDATE_PT
CREATE TRIGGER TRIGGER_UPDATE_PT ON PHONGTRO
FOR INSERT,UPDATE
AS
BEGIN
	DECLARE @MAPT1 VARCHAR(5), @MAPT2 VARCHAR(5)

	SELECT @MAPT1=PT.MAPT, @MAPT2=KH.MAPT
	FROM INSERTED PT, KHACHHANG KH
	WHERE PT.MAKH=KH.MAKH

	IF (@MAPT1!=@MAPT2)
		BEGIN
			PRINT 'ERROR!'
			ROLLBACK TRAN
		END
	ELSE
		PRINT 'THANH CONG'
END

INSERT INTO PHONGTRO VALUES ('PT004', 'CN03', '900000',	'KH03')
INSERT INTO KHACHHANG VALUES ('KH03', 'Huynh Thi C', 'Nha Trang', '331122004', 'PT003')

CREATE TRIGGER TRG_KHACHHANG ON KHACHHANG
FOR UPDATE
AS BEGIN
	IF EXISTS (SELECT * FROM INSERTED KH, PHONGTRO PT
			   WHERE KH.MAKH = PT.MAKH
			   AND KH.MAPT != PT.MAPT)
		BEGIN
			PRINT 'LOI'
			ROLLBACK TRAN
		END
	ELSE
		BEGIN
			PRINT 'THANH CONG'
		END
END

UPDATE KHACHHANG
SET MAPT='PT002'
WHERE MAKH='KH03'
DROP TRIGGER T_KH_PT
SELECT *FROM PHONGTRO

CREATE TRIGGER T_KH_PT ON PHONGTRO 
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAPT VARCHAR(4), @MAKH VARCHAR(4)
	SELECT @MAKH = MAKH
	FROM INSERTED

	IF((
	SELECT KH.MAKH
	FROM KHACHHANG KH, inserted I
	WHERE I.MAPT = KH.MAPT) != @MAKH)
	
	BEGIN
		PRINT 'ERROR'
		ROLLBACK TRAN
	END
	ELSE
	PRINT 'OK'
END
INSERT INTO PHONGTRO VALUES ('PT004', 'CN03', '900000',	'KH03')
DELETE FROM PHONGTRO WHERE MAPT='PT004'
--4.Tìm các khách hàng đã ở trọ tại các phòng của chủ nhà ‘Le Cong D’ vào tháng 2 năm 2019 (TENKH, CMND).(1đ)
SELECT TENKH, KH.CMND
FROM KHACHHANG KH, PHONGTRO PT, CHUNHA CN, THANHTOAN TT
WHERE KH.MAKH=PT.MAKH AND PT.MACN=CN.MACN AND TT.MAKH=KH.MAKH
      AND TENCN='Le Cong D' AND MONTH(NGAYNOP)=2 AND YEAR(NGAYNOP)=2019
--5.Tìm phòng trọ thu được số tiền thuê nhiều nhất trong năm 2019 (MAPT, SOTIENTHUE). (1đ)
--(Chỉ cần tìm 1 phòng, không cần liệt kê tất cả các phòng có cùng sô tiền thuê cao nhất) 
SELECT TOP 1 MAPT, SUM(SOTIEN) AS SOTIENTHUE
FROM THANHTOAN TT
WHERE YEAR(NGAYNOP)=2019
GROUP BY MAPT
ORDER BY SUM(SOTIEN) DESC

--6.Liệt kê phòng trọ và những người đang ở trọ trong đó (nếu có) (MAPT, TENCN, TENKH). (1đ).
SELECT PT.MAPT, TENCN, TENKH
FROM PHONGTRO PT
LEFT JOIN CHUNHA CN ON PT.MACN=CN.MACN
LEFT JOIN KHACHHANG KH ON KH.MAKH = PT.MAKH

SELECT PT.MAPT, TENCN, TENKH
FROM CHUNHA CN
JOIN PHONGTRO PT ON PT.MACN=CN.MACN
LEFT JOIN KHACHHANG KH ON KH.MAKH = PT.MAKH

SELECT DISTINCT A.MAPT, A.TENCN, TENKH
FROM 
	(
	SELECT CN.TENCN, PT.MAPT
	FROM PHONGTRO PT, CHUNHA CN -- KẾT VS CHỦ NHÀ ĐỂ LẤY TÊN CHỦ NHÀ
	WHERE PT.MACN = CN.MACN) AS A
LEFT JOIN
	(
	SELECT PT.MAPT, TENCN, TENKH
	FROM KHACHHANG KH, THANHTOAN TT, CHUNHA CN, PHONGTRO PT
	WHERE TT.MAPT = PT.MAPT AND PT.MACN = CN.MACN AND PT.MAKH = KH.MAKH) AS B
ON A.MAPT = B.MAPT

--7.Tìm khách hàng đã từng ở qua tất cả các phòng trọ (MAKH, TENKH) (1đ).
SELECT MAKH, TENKH
FROM KHACHHANG KH
WHERE NOT EXISTS(SELECT *
                 FROM PHONGTRO PT
				 WHERE NOT EXISTS(SELECT *
				                  FROM THANHTOAN TT
								  WHERE TT.MAKH=KH.MAKH AND TT.MAPT=PT.MAPT))

