DROP DATABASE QLNX

CREATE DATABASE QLNX

USE QLNX

CREATE TABLE NHACUNGCAP
(
	MANCC VARCHAR(5) CONSTRAINT PK_NCC PRIMARY KEY,
	TENNCC VARCHAR(50),
	QUOCGIA VARCHAR(30),
	LOAINCC VARCHAR(20)
)

CREATE TABLE DUOCPHAM
(
	MADP VARCHAR(5) CONSTRAINT PK_DP PRIMARY KEY,
	TENDP VARCHAR(50),
	LOAIDP VARCHAR(20),
	GIA MONEY
)

CREATE TABLE PHIEUNHAP
(
	SOPN VARCHAR(5) CONSTRAINT PK_PN PRIMARY KEY,
	NGNHAP SMALLDATETIME,
	MANCC VARCHAR(5),
	LOAINHAP VARCHAR(30)
)

CREATE TABLE CTPN
(
	SOPN VARCHAR(5),
	MADP VARCHAR(5),
	SOLUONG INT,
	CONSTRAINT PK_CT PRIMARY KEY(SOPN, MADP)
)

ALTER TABLE PHIEUNHAP
ADD CONSTRAINT FK_PN_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)

ALTER TABLE CTPN
ADD CONSTRAINT FK_CT_PN FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN)

ALTER TABLE CTPN
ADD CONSTRAINT FK_CT_DP FOREIGN KEY (MADP) REFERENCES DUOCPHAM(MADP)

SET DATEFORMAT DMY

INSERT INTO NHACUNGCAP VALUES('NCC01' ,'Phuc Hung', 'Viet Nam', 'Thuong xuyen')
INSERT INTO NHACUNGCAP VALUES('NCC02' ,'J. B. Pharmaceuticals', 'India', 'Vang lai')
INSERT INTO NHACUNGCAP VALUES('NCC03', 'Sapharco', 'Singapore', 'Vang lai')
INSERT INTO NHACUNGCAP VALUES('NCC04', 'Sapharco', 'Singapore', 'A')

INSERT INTO DUOCPHAM VALUES('DP01', 'Thuoc ho PH', 'Siro', '120000')
INSERT INTO DUOCPHAM VALUES('DP02', 'Zecuf Herbal CouchRemedy', 'Vien nen', '200000')
INSERT INTO DUOCPHAM VALUES('DP03', 'Cotrim', 'Vien sui', '80000')

INSERT INTO PHIEUNHAP VALUES ('00001', '22/11/2017', 'NCC01', 'Noi dia')
INSERT INTO PHIEUNHAP VALUES ('00002', '04/12/2017', 'NCC03', 'Nhap khau')
INSERT INTO PHIEUNHAP VALUES ('00003', '10/12/2017', 'NCC02', 'Nhap khau')
INSERT INTO PHIEUNHAP VALUES ('00004', '10/12/2017', 'NCC04', 'Nhap khau')
INSERT INTO PHIEUNHAP VALUES ('00005', '10/12/2017', 'NCC04', 'Nhap khau')

DELETE FROM PHIEUNHAP WHERE SOPN='00004'
INSERT INTO CTPN VALUES('00001', 'DP01', '100')
INSERT INTO CTPN VALUES('00001', 'DP02', '200')
INSERT INTO CTPN VALUES('00003', 'DP03', '543')
INSERT INTO CTPN VALUES('00004', 'DP03', '543')
INSERT INTO CTPN VALUES('00005', 'DP01', '543')

--3. Hiện thực ràng buộc toàn vẹn sau: Tất cả các dược phẩm có loại là Siro đều có giá lớn hơn 
--100.000đ(1đ).

ALTER TABLE DUOCPHAM
ADD CONSTRAINT CK_DP CHECK(LOAIDP !='Siro' OR (LOAIDP='Siro' AND GIA>100000))
ALTER TABLE DUOCPHAM
DROP CONSTRAINT CK_DP
INSERT INTO DUOCPHAM VALUES('DP04', 'Cotrim', 'S', '80000')
DELETE FROM DUOCPHAM WHERE MADP='DP04'
CREATE TRIGGER TRIGGER_INSERT_UPDATE_DP ON DUOCPHAM
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @LOAIDP VARCHAR(20), @GIA MONEY

	SELECT @LOAIDP=LOAIDP, @GIA=GIA
	FROM INSERTED
	
	IF(@LOAIDP='Siro')
		IF(@GIA<=100000)
			BEGIN
				PRINT 'ERROR!'
				ROLLBACK TRAN
			END
		ELSE
			PRINT 'THANH CONG'
END
INSERT INTO DUOCPHAM VALUES('DP04', 'Cotrim', 'Siro', '800000')
UPDATE DUOCPHAM
SET GIA='110000'
WHERE MADP='DP04'
DELETE FROM DUOCPHAM WHERE MADP='DP04'
--4. Hiện thực ràng buộc toàn vẹn sau: Phiếu nhập của những nhà cung cấp ở những quốc gia
--khác Việt Nam đều có loại nhập là Nhập khẩu. (2đ)
--TRIGGER ON PHIEUNHAP
CREATE TRIGGER TRIGGER_INSERT_UPDATE_PN ON PHIEUNHAP
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @QUOCGIA VARCHAR(30), @LOAINHAP VARCHAR(30)
	
	SELECT @QUOCGIA=QUOCGIA, @LOAINHAP=LOAINHAP
	FROM INSERTED PN, NHACUNGCAP NCC
	WHERE PN.MANCC=NCC.MANCC

	IF(@QUOCGIA!='Viet Nam')
		IF(@LOAINHAP != 'Nhap khau')
			BEGIN
				PRINT 'ERROR!'
				ROLLBACK TRAN
			END
		ELSE
			PRINT 'THANH CONG'
END

INSERT INTO PHIEUNHAP VALUES ('00004', '10/12/2017', 'NCC01', 'Noi dia')
delete from PHIEUNHAP where SOPN='00004'
select * from PHIEUNHAP
UPDATE PHIEUNHAP
SET MANCC='NCC02'
WHERE SOPN='00004'
--TRIGGER ON NHACUNGCAP

CREATE TRIGGER TRIGGER_UPDATE_NCC ON NHACUNGCAP
FOR UPDATE
AS
BEGIN
	IF EXISTS(SELECT *
	          FROM INSERTED NCC, PHIEUNHAP PN
			  WHERE NCC.MANCC=PN.MANCC AND QUOCGIA!='Viet Nam' AND LOAINHAP !='Nhap khau')
		BEGIN
			PRINT 'ERROR!'
			ROLLBACK TRAN
		END
	ELSE
		PRINT 'THANH CONG'
END

UPDATE NHACUNGCAP
SET QUOCGIA='d'
WHERE MANCC='ncc01'

--5. Tìm tất cả các phiếu nhập có ngày nhập trong tháng 12 năm 2017, sắp xếp kết quả tăng dần 
--theo ngày nhập (1đ).
SELECT SOPN
FROM PHIEUNHAP
WHERE MONTH(NGNHAP)=12 AND YEAR(NGNHAP)=2017
ORDER BY NGNHAP ASC
--6. Tìm dược phẩm được nhập số lượng nhiều nhất trong năm 2017 (1đ).
SELECT DP.MADP, TENDP
FROM DUOCPHAM DP, CTPN CT, PHIEUNHAP PN
WHERE DP.MADP=CT.MADP AND CT.SOPN=PN.SOPN AND YEAR(NGNHAP)=2017
GROUP BY DP.MADP, TENDP
HAVING SUM(SOLUONG) >= ALL (SELECT SUM(SOLUONG)
                            FROM CTPN CT, PHIEUNHAP PN
							WHERE CT.SOPN=PN.SOPN AND YEAR(NGNHAP)=2017
							GROUP BY MADP)

SELECT TOP 1 WITH TIES DP.MADP, TENDP
FROM DUOCPHAM DP, CTPN CT, PHIEUNHAP PN
WHERE DP.MADP=CT.MADP AND CT.SOPN=PN.SOPN AND YEAR(NGNHAP)=2017
GROUP BY DP.MADP, TENDP
ORDER BY SUM(SOLUONG) DESC
--7. Tìm dược phẩm chỉ có nhà cung cấp thường xuyên (LOAINCC là Thuong xuyen) cung cấp, 
--nhà cung cấp vãng lai (LOAINCC là Vang lai) không cung cấp. (1đ)

--SELECT DP.MADP, TENDP
--FROM DUOCPHAM DP, CTPN CT, PHIEUNHAP PN, NHACUNGCAP NCC
--WHERE DP.MADP=CT.MADP AND CT.SOPN=PN.SOPN AND PN.MANCC=NCC.MANCC
--      AND LOAINCC='Thuong xuyen'
--EXCEPT
--SELECT DP.MADP, TENDP
--FROM DUOCPHAM DP, CTPN CT, PHIEUNHAP PN, NHACUNGCAP NCC
--WHERE DP.MADP=CT.MADP AND CT.SOPN=PN.SOPN AND PN.MANCC=NCC.MANCC
--      AND LOAINCC='Vang lai'

SELECT DP.MADP, TENDP
FROM DUOCPHAM DP, CTPN CT
WHERE DP.MADP=CT.MADP 
EXCEPT
SELECT DP.MADP, TENDP
FROM DUOCPHAM DP, CTPN CT, PHIEUNHAP PN, NHACUNGCAP NCC
WHERE DP.MADP=CT.MADP AND CT.SOPN=PN.SOPN AND PN.MANCC=NCC.MANCC
      AND LOAINCC!= 'Thuong xuyen'
--8. Tìm nhà cung cấp đã từng cung cấp tất cả những dược phẩm có giá trên 100.000đ
--trong năm 2017 (1đ).
SELECT MANCC, TENNCC
FROM NHACUNGCAP NCC
WHERE NOT EXISTS (SELECT *
                  FROM DUOCPHAM DP, CTPN CT
				  WHERE DP.MADP=CT.MADP AND GIA>100000 
				        AND NOT EXISTS (SELECT *
						                FROM PHIEUNHAP PN
										WHERE PN.MANCC=NCC.MANCC AND PN.SOPN=CT.SOPN))
SELECT MANCC, TENNCC
FROM NHACUNGCAP NCC
WHERE NOT EXISTS (SELECT *
                  FROM DUOCPHAM DP
				  WHERE GIA>100000 
				        AND NOT EXISTS (SELECT *
						                FROM PHIEUNHAP PN, CTPN CT
										WHERE DP.MADP=CT.MADP AND PN.MANCC=NCC.MANCC AND PN.SOPN=CT.SOPN
										      AND YEAR(NGNHAP)=2017))
SELECT MANCC
FROM PHIEUNHAP PN
WHERE YEAR(NGNHAP) = 2017
	  AND NOT EXISTS (SELECT MADP FROM DUOCPHAM DP
					  WHERE GIA > 100000
                            AND NOT EXISTS (SELECT MADP FROM CTPN CT
											WHERE CT.SOPN = PN.SOPN
											AND DP.MADP = CT.MADP))