CREATE DATABASE QLCUAHANGXEDAP

USE QLCUAHANGXEDAP

CREATE TABLE KHACHHANG
(
	MA_KHACHHANG VARCHAR(5) CONSTRAINT PK_KH PRIMARY KEY,
	TEN VARCHAR(10),
	HO VARCHAR(10),
	SO_DIENTHOAI VARCHAR(20),
	EMAIL VARCHAR(50),
	DUONG_DIACHI VARCHAR(50),
	TP_DIACHI VARCHAR(30),
	BANG_DIACHI VARCHAR(30),
	MA_BUUCHINH VARCHAR(5),
)

CREATE TABLE NHANVIEN
(
	MA_NHANVIEN VARCHAR(5) CONSTRAINT PK_NV PRIMARY KEY,
	TEN VARCHAR(10),
	HO VARCHAR(10),
	EMAIL VARCHAR(50),
	SO_DIENTHOAI VARCHAR(20),
	DANG_LAMVIEC INT,
	MA_CUAHANG VARCHAR(5),
	MA_NGUOIQL VARCHAR(5)
)

CREATE TABLE NHASX
(
	MA_NHASX VARCHAR(5) CONSTRAINT PK_NSX PRIMARY KEY,
	TEN_NHASX VARCHAR(50),
)

CREATE TABLE LOAISP
(
	MA_LOAISP VARCHAR(5) CONSTRAINT PK_LSP PRIMARY KEY,
	TEN_LOAISP VARCHAR(50),
)

CREATE TABLE SANPHAM
(
	MA_SANPHAM VARCHAR(5) CONSTRAINT PK_SP PRIMARY KEY,
	TEN_SANPHAM VARCHAR(50),
	MA_NHASX VARCHAR(5),
	MA_LOAISP VARCHAR(5),
	NAM INT,
	GIABAN MONEY
)

CREATE TABLE KHO
(
	MA_CUAHANG VARCHAR(5),
	MA_SANPHAM VARCHAR(5),
	SOLUONG INT,
	CONSTRAINT PK_KHO PRIMARY KEY(MA_CUAHANG, MA_SANPHAM)
)

CREATE TABLE CUAHANG
(
	MA_CUAHANG VARCHAR(5) CONSTRAINT PK_CH PRIMARY KEY,
	TEN_CUAHANG VARCHAR(50),
	SO_DIENTHOAI VARCHAR(20),
	EMAIL VARCHAR(50),
	DUONG_DIACHI VARCHAR(50),
	TP_DIACHI VARCHAR(30),
	BANG_DIACHI VARCHAR(30),
	MA_BUUCHINH VARCHAR(5),
)

CREATE TABLE HOADON
(
	SO_HOADON VARCHAR(5) CONSTRAINT PK_HD PRIMARY KEY,
	MA_KHACHHANG VARCHAR(5),
	TRANGTHAI_HOADON VARCHAR(20),
	NGAY_HOADON SMALLDATETIME,
	NGAY_GHDUKIEN SMALLDATETIME,
	NGAY_GHTHUCTE SMALLDATETIME,
	MA_CUAHANG VARCHAR(5),
	MA_NHANVIEN VARCHAR(5)
)

CREATE TABLE CTHD
(
	SO_HOADON VARCHAR(5),
	MA_CHIECXE VARCHAR(5),
	MA_SANPHAM VARCHAR(5),
	SOLUONG INT,
	GIABAN MONEY,
	GIAMGIA INT,
	CONSTRAINT PK_CT PRIMARY KEY(SO_HOADON,MA_CHIECXE)
)

ALTER TABLE NHANVIEN
ADD CONSTRAINT A FOREIGN KEY (MA_CUAHANG) REFERENCES CUAHANG(MA_CUAHANG)

ALTER TABLE NHANVIEN
ADD CONSTRAINT B FOREIGN KEY (MA_NGUOIQL) REFERENCES NHANVIEN(MA_NHANVIEN)

ALTER TABLE SANPHAM
ADD CONSTRAINT C FOREIGN KEY (MA_NHASX) REFERENCES NHASX(MA_NHASX)

ALTER TABLE SANPHAM
ADD CONSTRAINT D FOREIGN KEY (MA_LOAISP) REFERENCES LOAISP(MA_LOAISP)

ALTER TABLE KHO
ADD CONSTRAINT E FOREIGN KEY (MA_CUAHANG) REFERENCES CUAHANG(MA_CUAHANG)

ALTER TABLE KHO
ADD CONSTRAINT F FOREIGN KEY (MA_SANPHAM) REFERENCES SANPHAM(MA_SANPHAM)

ALTER TABLE HOADON
ADD CONSTRAINT G FOREIGN KEY (MA_KHACHHANG) REFERENCES KHACHHANG(MA_KHACHHANG)

ALTER TABLE HOADON
ADD CONSTRAINT H FOREIGN KEY (MA_CUAHANG) REFERENCES CUAHANG(MA_CUAHANG)

ALTER TABLE HOADON
ADD CONSTRAINT I FOREIGN KEY (MA_NHANVIEN) REFERENCES NHANVIEN(MA_NHANVIEN)

ALTER TABLE CTHD
ADD CONSTRAINT K FOREIGN KEY (SO_HOADON) REFERENCES HOADON(SO_HOADON)

ALTER TABLE CTHD
ADD CONSTRAINT L FOREIGN KEY (MA_CHIECXE) REFERENCES SANPHAM(MA_SANPHAM)

ALTER TABLE CTHD
ADD CONSTRAINT M FOREIGN KEY (MA_SANPHAM) REFERENCES SANPHAM(MA_SANPHAM)

--1. Hiện thực ràng buộc toàn vẹn sau: Sản phẩm có năm sản xuất từ 2021 trở đi phải có giá bán
--lớn hơn 5500 (1đ).
--ALTER TABLE SANPHAM
--ADD CONSTRAINT KT_SP_GB CHECK(NAM>=2021 AND GIABAN>5500)
CREATE TRIGGER TRIGGER_SANPHAM ON SANPHAM
FOR INSERT, UPDATE 
AS BEGIN
	DECLARE @nam INT, @giaBan MONEY
	SET @nam = (SELECT nam FROM INSERTED)
	SET @giaBan = (SELECT giaBan FROM INSERTED)
	IF (@nam >= 2021)
		IF (@giaBan < 5500)
		BEGIN 
			PRINT 'NHAP KHONG THANH CONG'
			ROLLBACK TRAN
		END
		ELSE
			BEGIN PRINT 'NHAP THANH CONG'
		END
	END

--2. Hiện thực ràng buộc toàn vẹn sau: Số điện thoại của nhân viên và khách hàng không được
--giống nhau (2đ).
CREATE TRIGGER TRIGGER_INSERT_UPDATE_NV ON HOADON
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @SODTNV VARCHAR(20), @SODTKH VARCHAR(20)

	SELECT @SODTNV=NV.S0_DIENTHOAI, @SODTKH=KH.SO_DIENTHOAI
	FROM INSERTED HD, KHACHHANG KH, NHANVIEN NV
	WHERE NV.MA_NHANVIEN=HD.MA_NHANVIEN AND HD.MA_KHACHHANG=KH.MAKHACHHANG

	IF(@SODTKH=@SODTKH)
		BEGIN
			PRINT 'ERROR'
			ROLLBACK TRAN
		END
	ELSE
		PRINT 'THANH CONG'
END

CREATE TRIGGER UPDATE_SODT_NHANVIEN ON NHANVIEN
FOR UPDATE 
AS
BEGIN
	IF EXISTS (SELECT * FROM inserted I, HOADON HD, KHACHHANG KH 
	           WHERE I.MA_NHANVIEN = HD.MA_NHANVIEN AND HD.MA_KHACHHANG = KH.MA_KHACHHANG AND 
			         KH.SO_DIENTHOAI = I.SO_DIENTHOAI)
	BEGIN
		RAISERROR('LOI: SO DIEN THOAI NV TRUNG VOI SDT KHACHHANG!', 16, 1)
		ROLLBACK TRAN
	END
END


CREATE TRIGGER UPDATE_SODT_KHACHHANG ON KHACHHANG
FOR UPDATE 
AS
BEGIN
	IF EXISTS (SELECT * FROM inserted I, HOADON HD, NHANVIEN NV 
	           WHERE I.MA_KHACHHANG = HD.MA_KHACHHANG AND HD.MA_NHANVIEN = NV.MA_NHANVIEN AND 
			         I.SO_DIENTHOAI = NV.SO_DIENTHOAI)
	BEGIN
		RAISERROR('LOI: SO DIEN THOAI NV TRUNG VOI SDT KHACHHANG!', 16, 1)
		ROLLBACK TRAN
	END
END

--3. Tìm thông tin các hóa đơn có ngày giao hàng thực tế lớn hơn ngày giao hàng dự kiến (1đ).
SELECT SOHD
FROM HOADON
WHERE NG_GHTHUCTE > NG_GHDUKIEN

--4. Liệt kê các sản phẩm được hãng Strider sản xuất ra từ năm 2018 trở đi (1đ).
SELECT MASANPHAM, TEN_SANPHAM
FROM SANPHAM SP, NHASX NSX
WHERE SP.MA_NHASX=NSX.MA_NHASX AND TEN_NHASX='Strider' AND NAM >=2018

--5. In ra danh sách các khách hàng của các cửa hàng ở tiểu bang TX (Texas) (1đ).
--SELECT CH.MA_CUAHANG, MA_KHACHHANG
--FROM HOADON HD, CUAHANG CH
--WHERE HD.MA_CUAHANG=CH.MA_CUAHANG AND BANG_DIACHI='TX'
--GROUP BY CH.MA_CUAHANG, MA_KHACHHANG

SELECT KH.MA_KHACHHANG, HO, TEN
FROM KHACHHANG KH, HOADON HD, CUAHANG CH
WHERE HD.MA_CUAHANG = CH.MA_CUAHANG AND 
      HD.MA_KHACHHANG = KH.MA_KHACHHANG AND
	  CH.BANG_DIACHI='TX'

--6. In ra danh sách các sản phẩm có giá từ 4000 trở lên do nhân viên có tên là Kali bán được
--(1đ).
--SELECT SP.MA_SANPHAM, TEN_SANPHAM
--FROM SANPHAM SP, HOADON HD, NHANVIEN NV
--WHERE SP.MA_KHACHHANG=HD.MA_KHACHHANG AND HD.MA_NHANVIEN=NV.MA_NHANVIEN
--      AND GIABAN>=4000 AND TEN='Kali'

SELECT SP.MA_SANPHAM, TEN_SANPHAM
FROM SANPHAM SP, HOADON HD, NHANVIEN NV, CTHD CT 
WHERE SP.MA_SANPHAM = CT.MA_SANPHAM AND 
      CT.SO_HOADON = HD.SO_HOADON AND
	  HD.MA_NHANVIEN = NV.MA_NHANVIEN AND
	  CT.GIABAN >= 4000 AND 
	  TEN='Kali'

--7. Tìm khách hàng chỉ mua duy nhất những sản phẩm của nhà sản xuất Haro (1đ).
--SELECT MA_KHACHHANG
--FROM NHASX NSX, SANPHAM SP, HOADON HD, CTHD CT
--WHERE HD.SO_HOADON = CT.SO_HOADON AND 
--      CT.MA_SANPHAM = SP.MA_SANPHAM AND 
--      SP.MA_NHASX = NSX.MA_NHASX AND 
--	  TEN_NHASX = 'Haro'

SELECT MA_KHACHHANG
FROM NHASX NSX, SANPHAM SP, HOADON HD, CTHD CT
WHERE HD.SO_HOADON = CT.SO_HOADON AND 
      CT.MA_SANPHAM = SP.MA_SANPHAM AND 
      SP.MA_NHASX = NSX.MA_NHASX AND 
	  TEN_NHASX = 'Haro'

--8. Tìm các nhân viên bán được ít xe đạp thuộc loại Cyclocross Bicycles nhất (1đ).
SELECT MA_NHANVIEN
FROM HOADON HD, CTHD CT, SANPHAM SP, LOAISP LSP
WHERE HD.SO_HOADON = CT.SO_HOADON AND 
      CT.MA_SANPHAM = SP.MA_SANPHAM AND
	  SP.MA_LOAISP = LSP.MA_LOAISP AND 
	  TEN_LOAISP='Cyclocross Bicycles'
GROUP BY MA_NHANVIEN
HAVING COUNT(CT.SO_HOADON) <= ALL(SELECT COUNT(SO_HOADON)
							      FROM HOADON HD, CTHD CT, SANPHAM SP, LOAISP LSP
							      WHERE HD.SO_HOADON = CT.SO_HOADON AND 
								        CT.MA_SANPHAM= SP.MA_SANPHAM AND
							            SP.MA_LOAISP= LSP.MA_LOAISP AND 
										TEN_LOAISP='Cyclocross Bicycles'
							      GROUP BY MA_NHANVIEN)

--9. Liệt kê những cửa hàng chứa trong kho tất cả các xe đạp của nhà sản xuất Sun Bicycles (1đ).
-- Phép chia
SELECT MA_CUAHANG, TEN_CUAHANG
FROM CUAHANG CH
WHERE NOT EXISTS (SELECT *
				  FROM SANPHAM SP, NHASX NSX
				  WHERE SP.MA_NHASX = NSX.MA_NHASX AND TEN_NHASX='Sun Bicycles'
				        AND NOT EXISTS(SELECT *
						               FROM KHO K
									   WHERE K.MA_CUAHANG = CH.MA_CUAHANG AND
									         K.MA_SANPHAM = SP.MA_SANPHAM))

